---
title: "mp4"
author: "Emily Morris"
date: "April 16, 2018"
output: html_document
---

```{r}

#install.packages("mdsr")
#install.packages("RMySQL")

library(mdsr)
library(RMySQL)
library(tidyverse)
library(dplyr)
whole_db <- dbConnect_scidb(dbname= "imdb")
library(ggplot2)
library(ggthemes)
library(animation)
#devtools::install_github("dgrtwo/gganimate")
library(gganimate)
library(magick)
#you need ImageMagick to make this work, and have to check off the "add legacy utilities" when installing it!!!!
```

```{r}
#sql queries for all imdb things based on books, the gross of everything made in America in dollars, and all movies and their titles/movie_ids

getmovie <- "SELECT movie_id
FROM movie_info
WHERE info_type_id = 92;"

getgross <- "SELECT substr(info, 1, locate('(', info) - 1) AS gross, movie_id
FROM movie_info
WHERE info_type_id= 107 AND info LIKE '%(USA)%' AND info LIKE '$%'"

gettitles <- "SELECT id AS movie_id, title, production_year AS year
FROM title
WHERE kind_id =1;"
```

```{r}
#running all those queries as objects

movie_ids <- whole_db %>%
dbGetQuery(getmovie)

movie_titles <- whole_db %>%
  dbGetQuery(gettitles)

movie_gross <- whole_db %>%
  dbGetQuery(getgross)
```

```{r}
#fixing the gross column so it's numeric instead of chr
movie_gross$gross_2 = gsub("[\\$,]", "", movie_gross$gross)
movie_gross$cash = as.numeric(movie_gross$gross_2)
```

```{r}
#getting inflation data (from US Consumer Price Index Website)
library(readxl)
cpi <- read_excel("cpi.xlsx")

cpi <- cpi %>%
  rename("year"="Year")%>%
  mutate(percent_inflation = Avg/100)

```

```{r}
#joining all the data sets in a way that we couldn't do all at once in SQL because it kept breaking the database when we tried (seemed ridiculous to have a huge sql query that took forever to test when we could sort what we needed from sql in smaller chunks and do the rest in dplyr)

movies <- movie_ids %>%
  left_join(movie_gross, by = "movie_id")%>%
  na.omit()%>%
  group_by(movie_id)%>%
  summarise(max_made = max(cash))%>%
  select(movie_id, max_made)%>%
  inner_join(movie_titles, by = "movie_id")%>%
  arrange(year)
```

```{r}
#Getting some statistics out of the data
movie_stats <- movies %>%
  group_by(year)%>%
  summarise(number_of_movies = n(),
            total_cash = sum(max_made),
            average_cash = mean(max_made))%>%
  left_join(cpi, by= "year")%>%
  mutate(total_made_adjusted = total_cash*percent_inflation,
         average_made_adjusted = average_cash*percent_inflation)
```

```{r}
#animating the average movie gross
average_gross_plot <- map(seq(nrow(movie_stats)), ~movie_stats[c(seq(.x), rep(.x, nrow(movie_stats) - .x)), ]) %>% 
    tweenr::tween_states(5, 2, 'cubic-in-out', 100) %>% 
    ggplot(aes(year, average_made_adjusted, frame = .frame)) + 
    geom_path() + 
    geom_point() +
    scale_y_log10()+
    xlab("Year") +
    ylab("Average Movie Gross Adjusted for Inflation (with 1982 as a baseline)")+
    theme_economist()+
    labs(title= "Average Gross for Movies Based Off Books 
from 1913 to 2017", subtitle= "Adjusted for inflation with 1982 as a consumer price index baseline")
    

animation::ani.options(interval = 0.1)
gganimate::gganimate(average_gross_plot, title_frame = FALSE)
```

```{r}
#animating the total movie gross
total_gross_plot <- map(seq(nrow(movie_stats)), ~movie_stats[c(seq(.x), rep(.x, nrow(movie_stats) - .x)), ]) %>% 
    tweenr::tween_states(5, 2, 'cubic-in-out', 100) %>% 
    ggplot(aes(year, total_made_adjusted, frame = .frame)) + 
    geom_path() + 
    geom_point() +
    scale_y_log10()+
    xlab("Year") +
    ylab("Total Movie Gross Adjusted for Inflation (with 1982 as a baseline)")+
    theme_economist()+
    labs(title= "Total Gross for Movies Based Off Books Per Year
from 1913 to 2017", subtitle= "Adjusted for inflation with 1982 as a consumer price index baseline")
    

animation::ani.options(interval = 0.1)
gganimate::gganimate(total_gross_plot, title_frame = FALSE)
```


Got the data for consumer price index from the US government website


https://community.rstudio.com/t/tweenr-gganimate-with-line-plot/4027/5
